src/openhmd.c

The title is self explanatory. As it stands a dereference is attempted before the pointer is checked for validity.

Moved the device pointer check to before any dereference is attempted.

---

src/drv_dummy/dummy.c
src/drv_oculus_rift/rift.c

We get warnings here when building OpenHMD with Blender, which is a bit annoying, so would be good to have it fixed in upstream. Forcing a signed enum would also work, but that would mean adding an unused value.

Quiet warning when using -Wformat-signedness

---

src/drv_oculus_rift/rift.c
src/openhmd.c

Updated patches after review in https://github.com/OpenHMD/OpenHMD/pull/58
I also made the error message print the actual unix device path, so you could run chmod to work around the rights issue if you like.

Fix some Oculus DK2 problems. Rev 2.

---

src/drv_oculus_rift/packet.c
src/drv_oculus_rift/rift.c

When enabling feature 4 (unknown so far, not used in any way by OpenHMD yet), the CV1 occasionally resets, leading to read errors in OpenHMD.
Not knowing the correct setup sequence to reliably enable feature 4, and not knowing what it is in the first place, disabling it makes OpenHMD reliably usable with the CV1.

Workaround the CV1 resetting issue

---

CMakeLists.txt
src/drv_osvr_hdk/osvr.c
src/drv_osvr_hdk/osvr.h

This PR does the following:
* Converts 16-bit fixed-point values to floats (for both the quaternion and acceleration vector).
* Fixes the use of a threading library in the CMake file (this makes it cross-platform). It failed to compile under OS X as it was.
Note that I haven't tested this beyond ensuring it compiles successfully.

OSVR HDK: Convert fixed-point values to floats.

---

src/drv_oculus_rift/rift.c
src/omath.c
src/omath.h

Here's code to use an asymmetric frustum and actually compute the FoV of the Rift devices from values reported by the hardware. The same technique can probably be applied to the other HMDs

Rift asymmetric frustum

---

src/omath.c

minor typo, looking between different implementations of glFrustum lead to missing 2! minus signs.  this patch adds them back and things look better.

oops, missing minus sign in make_frustum

---

src/Makefile.am
src/shaders.c
src/shaders.h

This fixes a bug whichcan lead to segfaults on some compilers/linkers .  Fixed the declaration to be extern int the header and const in the .c file so the linker always knows the size of the pointer and the string.

fixup types and extern handling for shader sources.

---

CMakeLists.txt
configure.ac
examples/opengl/CMakeLists.txt
examples/opengl/Makefile.am
examples/opengl/gl.c
examples/opengl/gl.h
examples/opengl/main.c

this updates the opengl example with a bunch of useful stuff.
- it sets the window based on the HMD reported resolution
- it uses the universal shader
- it adds crosshairs which you can use to estimate lens_sep on cv1 style adjustable IPD displays
- it allows disabling lens distortion
- it allows adjusting the distortion scale, in case of calibration FoV mismatches

Openglexample modernized

---

src/drv_oculus_rift/rift.c

When udev rules are not in place.
Add Wiki URL for udev setup.

rift: Fix buffer overflow

---

configure.ac
pkg-config/openhmd.pc.in

Let autoconf generate the pkg-config file has hidapi has not the same name on
the different platforms (hidapi or hidapi-libusb).
As we are working on the OpenHMD integration inside VLC media player, this is useful because our build system uses the OpenHMD pkg-config file to compile the VLC HMD plugin for all the platforms (even Windows).

Autoconf: do not hard-code the hidapi dependency in the pkg-config file

---

src/openhmd.c

Otherwise deadlock when trying to open a device after first open failed.
Signed-off-by: Mario Kleiner <mario.kleiner.de@gmail.com>

Add missing mutex unlock in error path.

---

CMakeLists.txt

It's required to link libopenhmd.a into a shared library and src/Makefile.am does this too:
libopenhmd_la_CPPFLAGS = -fPIC -I$(top_srcdir)/include -Wall

use position independent code with CMake too

---

src/drv_oculus_rift/packet.c
src/drv_oculus_rift/rift.c
src/drv_oculus_rift/rift.h

This pull request enables and manages the LED positions for the Oculus DK2 and CV1 including decoding of the LED positions.
This is needed for positional tracking.

Added LED management for Oculus DK2 and CV1

---

src/drv_htc_vive/packet.c

int and mz_ulong do not have the same size on some systems.

vive: fix a stack corruption in vive_decode_config_packet

---

src/drv_nolo/packet.c

Visual Studio 14 does not support defining arrays with constants so I changed them to defines so I could compile them on my setup.

Change cryptwords and cryptoffset constants to define macros.

---

src/drv_psvr/psvr.c

Okay, so in an effort to improve the PSVR support on the driver, I noticed that the in the openglexample, there is a mode to test a crosshair overlay and it is very off-centre in PSVR. In order to adjust this, I took the measurements from https://github.com/gusmanb/PSVRFramework/wiki/Optical-characteristics, and I 'think' they're correct, but I would like to get a second opinion on this. They're likely an improvement over the previous values either way since they were just taken straight from the Vive verbatim.

Added modified lens measurements for PSVR.

---

meson.build

Pass the enabled -DDRIVER_* defines to the compiler, so the activated drivers
are actually registered.

Meson: actually use c_args

---

CMakeLists.txt

Missed a spot when renaming from HOLOLENS to WMR.

Fix cmake build for Windows Mixed Reality support

---

src/drv_oculus_rift/rift.c

Added GearVR Gen1 to the device list in the oculus driver, uses the exact same packet layout and is compatible with the current rift driver.
Is cheap hardware for testing!

GearVR (gen1) support

---

src/drv_wmr/wmr.c

Fixes a compiler warning:
drv_wmr/wmr.c: In function ‘open_device’:
drv_wmr/wmr.c:306:15: warning: pointer targets in passing argument 1 of ‘strncmp’ differ in signedness [-Wpointer-sign]

wmr: fix signedness compiler warning

---

src/drv_deepoon/deepoon.c
src/drv_htc_vive/vive_config.h
src/drv_nolo/nolo.c
src/drv_oculus_rift/rift.c
src/drv_psvr/psvr.c
src/drv_wmr/wmr.c
src/hid.h

There's still one warning left with gcc 7.3 when building via autotools or meson:
ext_deps/mjson.c: In function ‘json_read_array’:
ext_deps/mjson.c:612:2: warning: enumeration value ‘t_time’ not handled in switch [-Wswitch]
switch (arr->element_type) {
^~~~~~

Fix or hide most compiler warnings reported by gcc 7.3

---

.travis.yml

With the switch to the container-based travis workers for Linux, this doesn't even increase build times significantly.

Add Mac OSX build to travis

---

configure.ac
examples/opengl/gl.h

Extends the autoconf OpenGL check to fall back to find OpenGL framework, use the Mac OS X includes and add a glewInit stub, as GLEW is not used on Mac OS X. This fixes the OpenGL example build on travis-ci.org.

Fix OpenGL example autotools build for Mac OS X

---

src/drv_htc_vive/packet.c
src/drv_htc_vive/vive.c
src/drv_psvr/psvr.c
src/drv_wmr/wmr.c

Consistently using the LOG macros instead of printf directly could allow to add different logging backends or let applications provide a logging callback function.

Use LOG macros to log messages in drivers

---

examples/opengl/main.c
src/openhmd.c

Getting a bit tired of the opengl example segfaulting instead of displaying an error.

add permission error message and fix opengl example

---

src/openhmd.c

the getf function for ROTATION_QUAT applies rotation_correction twice, which seems quite wrong - likely to have escaped notice because the primary means of pulling a pose from OpenHMD is by using the MODELVIEW_MATRIX getfs.
There is a consistency fix to eliminate redundant tmp variable in one of the MODELMATRIX getfs too.

bugfix, plus consistency fix

---

meson.build

Make sure pkg-config --cflags output contains ${PREFIX}/include/openhmd,
which is where openhmd.h is installed.

Meson: add missing include subdir

---

CMakeLists.txt

This variable was not used so I removed it to simplify the CMakeLists.txt (I tested using MSVC).
Note that the correct variable to add a library prefix would be CMAKE_[TYPE]_PREFIX. I don't think that's a good idea to use it because an app CMake (and probably other tools) would not find the lib if it is prefixed. For example you would have to call find_library(**libopenhmd**) instead of find_library(**openmd**).

cmake : remove LIB_PREFIX variable

---

src/Makefile.am
src/openhmd.c

Hi,
while working on https://github.com/OpenHMD/OpenHMD/pull/165 i discovered, that the external driver will never be activated if autotools are used.
Furthermore i think that the external driver should be the driver with the second lowest priority, because the external driver always registers an HMD even if there is no one. Thereby it disables all following driver.
Kind regards,
Bernd

Fix external

---

src/drv_wmr/packet.c
src/drv_wmr/wmr.c
src/drv_wmr/wmr.h

A firmware update in Oct/Nov 2018 changed the protocol of the HoloLens Sensors
device slightly. The size of the sensor report is reduced and debug messages
are now moved into a separate report.

wmr: fix for firmware update

---

include/openhmd.h

There was a missed copy-paste and the documentation of ohmd_required_version is invalid.

openhmd: fix documentation of ohmd_require_version

---

meson.build

Generate the openhmd.pc pkgconfig file and install it and the openhmd.h
header even when building a static library.
I don't really know why it was a different case, as you usually want this header and the .pc file whenever building a library.
I don't know if it should be the same for examples too, but I'm not too concerned. I can update the PR so as to build examples when building a static library too.

meson: build/install openhmd.pc and header in static lib

---

meson.build
src/drv_wmr/wmr.c

Fixed an error which would make meson and ninja unable to build `src/drv_wmr`. `src/ext-deps/nxjson.c` was not included before.

Fixed meson build

---

src/drv_htc_vive/vive.c

Based on the patch series from James Sarrett. "Add measured distortion coefficients and calculated asymmetric frustums."
I ran into problems from current master providing a way off FOV. The FOV and lens separation from Jason Sarrett's un-merged distortion patch is more accurate than what we have currently, which fixes some issues for me, relying on it.
Looks okay on my VIVE and VIVE Pro.

vive: Use calculated lens separation and FOV.

---

CMakeLists.txt

The defined cmake option is called "BUILD_BOTH_STATIC_SHARED_LIB", which is displayed in ccmake and other tools. The variable to decide on what to build is called "BUILD_BOTH_STATIC_SHARED_LIBS" though. This results in the listed cmake option having no effect.

Fixing a typo in an option name in CMakeLists.txt

---

meson.build
meson_options.txt

Add a `hidapi` combo option that can be set to `hidraw` or `libusb` on Linux to
choose the hidapi flavor. This allows to support Bluetooth HID devices such as
the Windows Mixed Reality Motion Controllers on Linux.

Meson: allow to use hidapi-hidraw on Linux

---

meson.build

Foreign platform compilation units are left empty after preprocessing, so we may just as well skip them altogether.

Meson: only include relevant platform compilation units

---

.appveyor.yml
examples/simple/simple.c
include/openhmd.h
meson.build
src/openhmd.c
src/platform-posix.c
src/platform-win32.c
subprojects/hidapi.wrap

I have added a local Meson wrap for the OpenHMD hidapi fork and somehow made it build on AppVeyor. This does not include the OpenGL example yet.

AppVeyor: build on Windows with MSVC

---

src/drv_nolo/nolo.c
src/drv_nolo/packet.c

Much cleaner version of #227 as it doesn't change the indentation of a large chunk of code.
The returned value of `is_nolo_device` could also be used in the driver for firmware-dependent code paths until proper detection is put in place.

Fixes old firmware version of the non-kickstarter NOLO CV1

---

.travis.yml

Try to avoid recent build failures caused by macOS builds
not installing dependencies due to an outdated homebrew.

travis: update homebrew on macOS

---

examples/simple/simple.c

The Rift remote buttons are assigned to the Rift HMD, and there are
other HMDs that have buttons, such as the PSVR volume controls and
the Vive system button.
Show controls on HMD class devices, if they have them.

examples/simple: allow controls on all device types

---

meson.build

Build the unit tests and hook them up to the ninja test target, fixes #248.

meson: hook up unit tests

---

CMakeLists.txt
README.md
meson.build
meson_options.txt
src/drv_oculus_rift/rift.c
src/drv_vrtek/packet.c
src/drv_vrtek/vrtek.c
src/drv_vrtek/vrtek.h
src/openhmd.c
src/openhmdi.h

This patchset adds basic support for the VR-Tek WVR3 and WVR2 headsets made by Direkt-tek. There is also a WVR1 that could be supported, but I don't have access to a WVR1 so for now only the two higher-end models are supported.
The distortion coefficients and aberration coefficients still need work (although to be honest the display output doesn't look too bad right now), but rotational tracking is working.
These are cheap and cheerful 3DoF headsets sold by Walmart in the US:
https://www.walmart.com/ip/VR-Tek-Windows-VR-Glasses-Ultra-HD-Resolution-1440x1400-Black/56206938
Emdoor VR is the actual OEM for the headsets, with:
* WVR1 -> SpearI FHD
* WVR2 -> SpearI 2K
* WVR3 -> SpearII
http://vr.emdoor.com/en/products/PC_VR/
The headsets are reusing the USB ID of the Oculus DK1, so I added a …

Add driver for the VR-Tek WVR headsets

---

src/drv_vrtek/vrtek.c

This fixes weird resolution distortion on the vrtek wvr3. Other headsets may require a fix as well, but I don't have other headsets to test and fix other parts of the driver.

Fix for vrtek wvr3 headset

---

meson.build

When building a static library, define OHMD_STATIC, else there would be
linker errors due to incorrect references to the functions with the
`__imp_` prefix.
Fix #245
Without this, OpenHMD itself will refer to some of the symbols with the
`__imp_` prefix causing erros like the following:
```
libopenhmd.a(src_openhmd.c.obj):openhmd.c:(.text+0xa20): undefined reference to `__imp_ohmd_list_open_device_s'
libopenhmd.a(src_openhmd.c.obj):openhmd.c:(.text+0xa20): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `__imp_ohmd_list_open_device_s'
libopenhmd.a(src_platform-win32.c.obj):platform-win32.c:(.text+0x132): undefined reference to `__imp_ohmd_sleep'
libopenhmd.a(src_platform-win32.c.obj):platform-win32.c:(.text+0x132): relocation truncated to fit: R_X86_64_PC32 against …
```

meson: Set OHMD_STATIC macro for static builds

---

meson.build
meson_options.txt

The option is enabled by default, but allows to disable building the unit tests
in case of linker issues on broken build systems.
Fixes #259.

meson: add an option to disable building the unit tests

---

src/drv_htc_vive/packet.c
src/drv_htc_vive/vive.c
src/drv_htc_vive/vive.h

This series of patches does some style consistency in the VIVE driver, refactoring and adds small features.
* Use tabs for indent consistently
* Even though it's not the case in the whole code base, I respect a 80 char limit, which didn't need much change anyway.
* Adds the ability to retrieve the firmware version.
* Cleans up default values for the IMU config. It does not try to get these on the Pro anymore, since it's not implemented.
* Makes the packet definition for the config structs more correct, as seen in ouvrt.
* The most controversial change is most likely to not use char buffers but the struct definitions to retrieve data using `hid_get_feature_report`, as it is usually done with libusb. Not sure why this wasn't done before or why this could introduce problems. I hope that this …

VIVE Improvements

---

src/platform.h

It is already defined and exported in the public openhmd header.

platform: remove ohmd_sleep

---

meson.build

Allow the use of OpenHMD as a subproject by declaring a meson
dependency in meson.build
By publishing a dependency variable, other projects that use meson can pull in OpenHMD as a wrapped subproject.

meson: Declare the openhmd_dep dependency

---

subprojects/hidapi.wrap

Updated hidapi.wrap to use revision [f19cb5e6ec30882b1367058e73a413b0b45636a2](https://github.com/OpenHMD/hidapi/commit/f19cb5e6ec30882b1367058e73a413b0b45636a2). This makes it easier to build master with Mingw-w64.

Updated hidapi revision to make it build on Mingw-w64

---

CMakeLists.txt

`nxjson` is missing when only building the Windows Mixed Reality driver via CMake. This pull request fixes this issue.

Fix WMR driver build via CMake

---

CMakeLists.txt

Gets rid of a cmake warning on modern systems.

openhmd: Choose glvnd over legacy gl in cmake when available

---

src/drv_3glasses/xgvr.c
src/drv_htc_vive/packet.c
src/drv_htc_vive/vive.c
src/drv_nolo/nolo.c
src/drv_nolo/packet.c
src/drv_psvr/psvr.c
src/openhmd.c

Use the static keyword to hide internal functions and variables.

hide internal symbols

---

src/ext_deps/nxjson.c

When using OpenHMD under Linux within a QT based application, QT will set the locale to the locale selected by the user.
Since some countries use ',' as a decimal point and not '.' the JSON parser will fail since strtod() honors the locale set by QT.
This patch forces the locale to be 'C' and thus forcing strtod to work as required.

Force C locale before parsing JSON string

---

src/drv_oculus_rift/rift.c
src/drv_oculus_rift_s/rift-s.c

Fix crashes on closing devices after opening multiple ones by tracking the shared state counter correctly.

Rifts fix shutdown crashes

---

CMakeLists.txt

Checking with `nm -CD libopenhmd.so | grep " T "` shows the libopenhmd.so library built with cmake exports all defined functions (220 functions). With this change, it only exports the functions in the public openhmd API (22 functions).

openhmd: Only export public API in cmake

---

examples/opengl/main.c

Some improvements to the OpenGL example that I made while developing the Rift S driver - primarily the addition of a checkerboard floor that makes correct/incorrect distortion really easy to see.

Opengl example improvements

---

.appveyor.yml

Just as a suggestion for Windows but if you guys want to follow suit this would be good to do for Linux and Mac release packages too.
Add in the openhmd.h and openhmd.lib files so poor people like me can include OpenHMD in their projects without having to compile it themselves.

Include openhmd.h and openhmd.lib so you can download this as an SDK

---

src/drv_htc_vive/vive.c

just saw that reading the code, untested
reference
https://github.com/pH5/ouvrt/blob/446354fae08f9851658e92d31fe422d21fd3c47f/src/vive-imu.c#L129-L135

vive: Fix copy&paste error for gyro_bias

---

meson.build

If the library was built for static linking, the project compiling
against it will need to specify -DOHMD_STATIC when including the
headers on Windows, or the declspec symbol declarations are
incorrect.
Export the right cflags in the pkgconfig and declared
dependency object so that happens.

meson: If doing a static build, export that information.

---

src/drv_nolo/nolo.c

The device class for the nolo head tracker was set to an HMD.  This causes problems on dependant projects like Monado which expects HMDs to include display devices.
The nolo head tracker is not an HMD so this commit changes it to a generic tracker class.

Changed the device class of nolo head tracker.

---

meson.build

I wanted to build the project using only the Oculus Rift (CV1) drivers. Unfortunately, this did not work, since the `src/ext_deps/nxjson.c` file was wrongfully not included in the build sources of the Meson build file.
This pull request fixes that build issue and removes another redundant line from the `meson.build` file, which was likely added due to a copy and paste mistake.

Fixed build for building with just the Rift drivers
