- CMakeLists.txt
- cmake/FindHIDAPI.cmake
- Has the option to enable/disable drivers (Oculus and External currently)
- Automatically finds Hidapi when driver needs it (currently just Oculus)
> Added functional CMake buildfile.

- examples/opengl/main.c
- include/openhmd.h
- src/drv_external/external.c
- src/openhmd.c
- src/openhmdi.h
- src/platform-posix.c
- src/platform-win32.c
- src/platform.h
Merging of threading support of OpenHMD, polling and updating device in a seperate thread.
> Merge Threaded updates

- src/drv_oculus_rift/packet.c
- src/drv_oculus_rift/rift.c
- src/drv_oculus_rift/rift.h
Verified and tested, rotation works perfectly.
The packet still contains more unparsed data that could be used for positional tracking and (I guess) estimating latency.
> Add proper support for DK2/CV1 sensors

- src/drv_oculus_rift/packet.c
- src/drv_oculus_rift/rift.c
- src/drv_oculus_rift/rift.h
- src/fusion.c
Initial tilt correction was only applied if it exceeded an unreasonably high
angle using an unrelated constant (gravity_tolerance)
> Fix initial accelerometer-based tilt correction

- CMakeLists.txt
- configure.ac
- src/Makefile.am
- src/drv_deepoon/deepoon.c
- src/drv_nolo/nolo.c
- src/drv_nolo/nolo.h
- src/drv_nolo/packet.c
- src/openhmd.c
- src/openhmdi.h
Cleaned up by Jakob, all the heavy work by Joey, who based his on the work by Yann Vernier.
> Add NOLO driver.

- src/openhmd.c
- src/openhmdi.h
- src/platform-posix.c
- src/platform-win32.c
This lets you get raw ticks from ohmd and convert to whichever rate you want.
Cheers, Jakob.
> Add functions for integer monotonic ticks

- meson.build
- meson_options.txt
I'm sure it can be improved but as is, it works.
Example usage:
meson -DOPENHMD_EXAMPLE_SDL=true --prefix=$PWD/install --libdir=lib -Dbuildtype=release build
ninja -C build install
> add meson build

- examples/simple/simple.c
Gets rid of the warnings
[EE] invalid type given to getf (22d)
> examples/simple: Only query controller state if device is controller

- src/drv_psvr/psvr.c
This could use some more testing, it works for me (tm) on Linux and Windows 10.
The bogus PSVR device entries are gone and interfaces 4 and 5 are opened
regardless of device order with current hidapi master.
> psvr: match on interface_number

- examples/simple/simple.c
- include/openhmd.h
- src/drv_psvr/packet.c
- src/drv_psvr/psvr.c
- src/drv_psvr/psvr.h
Add button support, fix tick handling, read second IMU sample, improve gyro/accel scaling.
> PSVR button & second IMU sample support

- src/openhmd.c
See issue #160.
I still don't know it's a proper fix and it may break stuff for current users, so this needs feedback.
> potential fix for rotation + translation order

- meson.build
- meson_options.txt
Added LG-R100 device to meson build script
> Add LGR100 to meson

- meson.build
This removes the last bit of code checked for static vs dynamic builds in meson.
> meson: Make it possible to build all when building statically

- meson.build
- meson_options.txt
Meson is just python so format the file with pep8, this goes on top my `jakob-examples-static` branch.
> meson: Restyle meson files to be more readable

- src/drv_psvr/psvr.c
* Refactor the code and add some comments so it's easier to understand what the code is doing.
* Use all samples, a previous commit seems to have accidentally hardcoded only to use sample one.
* ~HTC PSVR~ Sony PSVR, oopsie.
* Add TODO about handling startup better after unclean session close.
> Some PSVR documentation and one fix

- .appveyor.yml
Package and upload artifacts (openhmd_simple_example.exe, openhmd-0.dll, and hidapi.dll) for easier testing.
> appveyor: package artifacts

- src/openhmd.c
Fixes: 2be3730d62ae ("potential fix for rotation + translation order")
> potential fix for rotation + translation order v2

- src/drv_nolo/nolo.c
- src/drv_nolo/nolo.h
- src/drv_nolo/packet.c
Merge of the dev-nolo branch driver for Nolo firmware >2.0 into the existing one
> Migration of both the nolo drivers for legacy (<2.0) and modern (>=2.0) firmware

- CMakeLists.txt
- meson.build
- src/Makefile.am
- src/drv_oculus_rift/packet.c
- src/drv_oculus_rift/rift-hmd-radio.c
- src/drv_oculus_rift/rift-hmd-radio.h
- src/drv_oculus_rift/rift.c
- src/drv_oculus_rift/rift.h
Publish extra devices for the Oculus Rift touch controllers, and add control outputs for the HMD device that output the remote button presses.
> Implement support for the Oculus Rift remote and touch controllers

- CMakeLists.txt
> rift: Fix CMake build

- CMakeLists.txt
- meson.build
- meson_options.txt
- src/drv_oculus_rift_s/rift-s-controller.c
- src/drv_oculus_rift_s/rift-s-controller.h
- src/drv_oculus_rift_s/rift-s-firmware.c
- src/drv_oculus_rift_s/rift-s-firmware.h
- src/drv_oculus_rift_s/rift-s-hmd.h
- src/drv_oculus_rift_s/rift-s-protocol.c
- src/drv_oculus_rift_s/rift-s-protocol.h
- src/drv_oculus_rift_s/rift-s-radio.c
- src/drv_oculus_rift_s/rift-s-radio.h
- src/drv_oculus_rift_s/rift-s.c
- src/drv_oculus_rift_s/rift-s.h
- src/hid.h
- src/openhmd.c
- src/openhmdi.h
This is a preliminary 3DOF driver for the Rift S headset and
controllers. Rotational IMU tracking and controller
controls are supported. It would also be possible to
publish more from the controllers with additional OpenHMD API,
such as capsense touch information for each button/trigger.
Distortion parameters are taken from the CV1 and need improving,
but aren't completely wrong.
> Initial 3DOF Oculus Rift S driver

- src/drv_3glasses/xgvr.c
- src/drv_deepoon/packet.c
- src/drv_wmr/wmr.c
There is some unused code that could be removed.
> Remove unused code

- src/drv_htc_vive/packet.c
- src/drv_oculus_rift/rift-hmd-radio.c
> Do not initialize NULL pointers with 0

- src/drv_deepoon/deepoon.c
- src/drv_nolo/nolo.c
- src/drv_oculus_rift/rift.c
- src/drv_vrtek/vrtek.c
- src/openhmd.c
- src/openhmdi.h
- src/utils.h
> Fix segfaults with null strings passed to wcscmp
